FROM quay.io/keycloak/keycloak:26.2

COPY KeycloakConfiguration/ /opt/keycloak/data/import/
COPY keycloak/themes/bugworx/ /opt/keycloak/themes/bugworx/

RUN /opt/keycloak/bin/kc.sh build --db=postgres

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD ["start", "--import-realm", "--optimized"]
