CREATE TABLE tenants (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL,
    modified_at TIMESTAMPTZ NOT NULL,
    created_by UUID NOT NULL,
    modified_by UUID NOT NULL,
    CONSTRAINT uq_tenants_slug UNIQUE (slug)
);

CREATE TABLE tenant_features (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INT NOT NULL,
    feature_key VARCHAR(100) NOT NULL,
    is_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL,
    modified_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_tenant_features_tenants FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT uq_tenant_features_tenant_id_feature_key UNIQUE (tenant_id, feature_key)
);
