CREATE TABLE cfg_employees (
    id                   INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id            INT          NOT NULL,
    name                 VARCHAR(255) NOT NULL,
    certification_number VARCHAR(100) NOT NULL,
    employee_number      VARCHAR(100) NOT NULL,
    role                 SMALLINT     NOT NULL,
    is_active            BOOLEAN      NOT NULL DEFAULT FALSE,
    is_deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMPTZ  NOT NULL,
    modified_at          TIMESTAMPTZ  NOT NULL,
    created_by           UUID         NOT NULL,
    modified_by          UUID         NOT NULL,
    CONSTRAINT fk_cfg_employees_tenants FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);
