-- Diagram: tbatch
CREATE TABLE Batches (
    Id INT NOT NULL PRIMARY KEY IDENTITY,
    OwnerId INT NOT NULL,
    CompanyId INT NOT NULL,
    BatchType TINYINT NOT NULL,
    Descr NVARCHAR(70),
    UtcCreateDate DATETIME NOT NULL,
    UtcClosedDate DATETIME,
    ClosedBy NVARCHAR(50),
    UtcLastUpdated DATETIME NOT NULL,
    AcctPeriodId INT,
    CreatedBy NVARCHAR(50) NOT NULL,
    IsDeleted BIT NOT NULL DEFAULT 0,
    CONSTRAINT FK_Batches_Company FOREIGN KEY (CompanyId) REFERENCES Companies(Id),
    CONSTRAINT FK_Batches_Period FOREIGN KEY (AcctPeriodId) REFERENCES AccountPeriods(Id)
);
GO

-- Diagram: tworkorderheader
CREATE TABLE WorkOrderHeaders (
    Id INT NOT NULL PRIMARY KEY IDENTITY,
    UtcTimestamp DATETIME NOT NULL,
    CreatedBy NVARCHAR(254) NOT NULL,
    ScheduleDate DATETIME,
    PrintedDate DATETIME,
    BatchId INT,
    ProgramId INT,
    LastChangedBy NVARCHAR(100) NOT NULL,
    UtcLastChanged DATETIME NOT NULL,
    ReleaseId INT,
    AssignedTo INT,
    CreateGroupId UNIQUEIDENTIFIER,
    TimeRangeId INT,
    Duration INT,
    ScheduleTime INT,
    Confirmed INT,
    ModifiedBy NVARCHAR(75),
    PoNumber NVARCHAR(100),
    IsDeleted BIT NOT NULL DEFAULT 0,
    CONSTRAINT FK_WorkOrderHeaders_Batch FOREIGN KEY (BatchId) REFERENCES Batches(Id),
    CONSTRAINT FK_WorkOrderHeaders_Program FOREIGN KEY (ProgramId) REFERENCES Programs(Id),
    CONSTRAINT FK_WorkOrderHeaders_Release FOREIGN KEY (ReleaseId) REFERENCES Releases(Id),
    CONSTRAINT FK_WorkOrderHeaders_TimeRange FOREIGN KEY (TimeRangeId) REFERENCES TimeRanges(Id)
);
GO

-- Diagram: tworkorderevent
CREATE TABLE WorkOrderEvents (
    Id INT NOT NULL PRIMARY KEY IDENTITY,
    BaseEventId INT NOT NULL,
    HeaderId INT NOT NULL,
    EventName NVARCHAR(50),
    BillAmount MONEY,
    CompletedAmount MONEY,
    SaleAmount MONEY,
    ProdAmount MONEY,
    DiscountAmount MONEY,
    TaxTypeName NVARCHAR(50),
    FederalTaxAmount MONEY,
    StateTaxAmount MONEY,
    LocalTaxAmount MONEY,
    JobInstructions NVARCHAR(MAX),
    BatchId INT,
    CompletedDate DATETIME,
    NoteToCustomer NTEXT,
    GeneratedDate DATETIME,
    OriginalDate DATETIME,
    GeneratedBy NVARCHAR(50),
    PrintDate DATETIME,
    GeneratedBatch UNIQUEIDENTIFIER,
    UtcTimestamp DATETIME NOT NULL,
    CreatedBy NVARCHAR(50) NOT NULL,
    UtcLastChanged DATETIME NOT NULL,
    LastChangedBy NVARCHAR(50) NOT NULL,
    SkippedDate DATETIME,
    DeletedDate DATETIME,
    TaxFedPercent DECIMAL(9, 8),
    TaxStatePercent DECIMAL(9, 8),
    TaxLocalPercent DECIMAL(9, 8),
    CreateGroupId UNIQUEIDENTIFIER,
    Duration INT,
    TaxTypeId INT,
    ServiceCenterId INT,
    SkipReason NTEXT,
    CompletedEmailDate DATETIME,
    CompletedPrintDate DATETIME,
    TechComments NVARCHAR(MAX),
    PurchaseOrder NVARCHAR(50),
    CancelReasonId INT,
    CancelReasonDesc NVARCHAR(MAX),
    IsDeleted BIT NOT NULL DEFAULT 0,
    CONSTRAINT FK_WorkOrderEvents_BaseEvent FOREIGN KEY (BaseEventId) REFERENCES Events(Id),
    CONSTRAINT FK_WorkOrderEvents_Header FOREIGN KEY (HeaderId) REFERENCES WorkOrderHeaders(Id),
    CONSTRAINT FK_WorkOrderEvents_Batch FOREIGN KEY (BatchId) REFERENCES Batches(Id),
    CONSTRAINT FK_WorkOrderEvents_TaxType FOREIGN KEY (TaxTypeId) REFERENCES TaxTypes(Id),
    CONSTRAINT FK_WorkOrderEvents_ServiceCenter FOREIGN KEY (ServiceCenterId) REFERENCES ServiceCenters(Id),
    CONSTRAINT FK_WorkOrderEvents_CancelReason FOREIGN KEY (CancelReasonId) REFERENCES CancelReasons(Id)
);
GO
