ALTER TABLE Tenants
    ALTER COLUMN CreatedAt TYPE TIMESTAMPTZ USING CreatedAt AT TIME ZONE 'UTC',
    ALTER COLUMN ModifiedAt TYPE TIMESTAMPTZ USING ModifiedAt AT TIME ZONE 'UTC';

ALTER TABLE TenantFeatures
    ALTER COLUMN CreatedAt TYPE TIMESTAMPTZ USING CreatedAt AT TIME ZONE 'UTC',
    ALTER COLUMN ModifiedAt TYPE TIMESTAMPTZ USING ModifiedAt AT TIME ZONE 'UTC';

ALTER TABLE Customers
    ALTER COLUMN CreatedAt TYPE TIMESTAMPTZ USING CreatedAt AT TIME ZONE 'UTC',
    ALTER COLUMN ModifiedAt TYPE TIMESTAMPTZ USING ModifiedAt AT TIME ZONE 'UTC';

ALTER TABLE CustomerContacts
    ALTER COLUMN CreatedAt TYPE TIMESTAMPTZ USING CreatedAt AT TIME ZONE 'UTC',
    ALTER COLUMN ModifiedAt TYPE TIMESTAMPTZ USING ModifiedAt AT TIME ZONE 'UTC';

ALTER TABLE CustomerContactPhones
    ALTER COLUMN CreatedAt TYPE TIMESTAMPTZ USING CreatedAt AT TIME ZONE 'UTC',
    ALTER COLUMN ModifiedAt TYPE TIMESTAMPTZ USING ModifiedAt AT TIME ZONE 'UTC';

ALTER TABLE ServiceAddresses
    ALTER COLUMN CreatedAt TYPE TIMESTAMPTZ USING CreatedAt AT TIME ZONE 'UTC',
    ALTER COLUMN ModifiedAt TYPE TIMESTAMPTZ USING ModifiedAt AT TIME ZONE 'UTC';
