CREATE TABLE OutboxMessages (
    Id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EventType   TEXT            NOT NULL,
    Payload     JSONB           NOT NULL,
    OccurredAt  TIMESTAMPTZ     NOT NULL,
    ProcessedAt TIMESTAMPTZ     NULL,
    Error       TEXT            NULL
);

CREATE INDEX IX_OutboxMessages_Unprocessed
    ON OutboxMessages (OccurredAt)
    WHERE ProcessedAt IS NULL AND Error IS NULL;
