CREATE TABLE estimates (
    id                 INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_address_id INT          NOT NULL,
    name               VARCHAR(255) NOT NULL,
    status             SMALLINT     NOT NULL,
    service_interest   VARCHAR(255),
    assigned_sales_rep INT          NOT NULL,
    source             SMALLINT     NOT NULL,
    is_deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMPTZ  NOT NULL,
    modified_at        TIMESTAMPTZ  NOT NULL,
    created_by         UUID         NOT NULL,
    modified_by        UUID         NOT NULL,
    CONSTRAINT fk_estimates_service_addresses FOREIGN KEY (service_address_id) REFERENCES service_addresses(id)
);
