CREATE TABLE cfg_routes (
    id              INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       INT          NOT NULL,
    cfg_employee_id INT          NOT NULL,
    name            VARCHAR(255) NOT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT FALSE,
    note            TEXT,
    is_deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ  NOT NULL,
    modified_at     TIMESTAMPTZ  NOT NULL,
    created_by      UUID         NOT NULL,
    modified_by     UUID         NOT NULL,
    CONSTRAINT fk_cfg_routes_tenants       FOREIGN KEY (tenant_id)       REFERENCES tenants(id),
    CONSTRAINT fk_cfg_routes_cfg_employees FOREIGN KEY (cfg_employee_id) REFERENCES cfg_employees(id)
);
