CREATE TABLE Estimates (
    Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ServiceAddressId INT NOT NULL,
    Name VARCHAR(255) NOT NULL,
    Status SMALLINT NOT NULL,
    ServiceInterest VARCHAR(255),
    AssignedSalesRep INT NOT NULL,
    Source SMALLINT NOT NULL,
    CreatedAt TIMESTAMPTZ NOT NULL,
    ModifiedAt TIMESTAMPTZ NOT NULL,
    CreatedBy UUID NOT NULL,
    ModifiedBy UUID NOT NULL,
    CONSTRAINT FK_Estimates_ServiceAddresses FOREIGN KEY (ServiceAddressId) REFERENCES ServiceAddresses(Id)
);
