CREATE TABLE cfg_estimates (
    id          INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   INT          NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    is_deleted  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL,
    modified_at TIMESTAMPTZ  NOT NULL,
    created_by  UUID         NOT NULL,
    modified_by UUID         NOT NULL,
    CONSTRAINT fk_cfg_estimates_tenants FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE TABLE cfg_programs (
    id          INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   INT          NOT NULL,
    name        VARCHAR(255) NOT NULL,
    is_deleted  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL,
    modified_at TIMESTAMPTZ  NOT NULL,
    created_by  UUID         NOT NULL,
    modified_by UUID         NOT NULL,
    CONSTRAINT fk_cfg_programs_tenants FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE TABLE cfg_events (
    id          INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   INT          NOT NULL,
    name        VARCHAR(255) NOT NULL,
    is_deleted  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL,
    modified_at TIMESTAMPTZ  NOT NULL,
    created_by  UUID         NOT NULL,
    modified_by UUID         NOT NULL,
    CONSTRAINT fk_cfg_events_tenants FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE TABLE cfg_cadences (
    id          INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   INT          NOT NULL,
    name        VARCHAR(255) NOT NULL,
    is_deleted  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL,
    modified_at TIMESTAMPTZ  NOT NULL,
    created_by  UUID         NOT NULL,
    modified_by UUID         NOT NULL,
    CONSTRAINT fk_cfg_cadences_tenants FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE TABLE cfg_program_event_cadences (
    id             INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      INT         NOT NULL,
    cfg_program_id INT         NOT NULL,
    cfg_event_id   INT         NOT NULL,
    cfg_cadence_id INT         NOT NULL,
    interval       NUMERIC     NOT NULL,
    is_deleted     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMPTZ NOT NULL,
    modified_at    TIMESTAMPTZ NOT NULL,
    created_by     UUID        NOT NULL,
    modified_by    UUID        NOT NULL,
    CONSTRAINT fk_cfg_program_event_cadences_tenants      FOREIGN KEY (tenant_id)      REFERENCES tenants(id),
    CONSTRAINT fk_cfg_program_event_cadences_cfg_programs FOREIGN KEY (cfg_program_id) REFERENCES cfg_programs(id),
    CONSTRAINT fk_cfg_program_event_cadences_cfg_events   FOREIGN KEY (cfg_event_id)   REFERENCES cfg_events(id),
    CONSTRAINT fk_cfg_program_event_cadences_cfg_cadences FOREIGN KEY (cfg_cadence_id) REFERENCES cfg_cadences(id)
);
