CREATE TABLE ops_estimates (
    id                 INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id          INT          NOT NULL,
    cfg_estimate_id    INT          NOT NULL,
    service_address_id INT          NOT NULL,
    status             SMALLINT     NOT NULL,
    service_interest   VARCHAR(255) NOT NULL,
    assigned_sales_rep INT          NOT NULL,
    source             SMALLINT     NOT NULL,
    is_deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMPTZ  NOT NULL,
    modified_at        TIMESTAMPTZ  NOT NULL,
    created_by         UUID         NOT NULL,
    modified_by        UUID         NOT NULL,
    CONSTRAINT fk_ops_estimates_tenants           FOREIGN KEY (tenant_id)          REFERENCES tenants(id),
    CONSTRAINT fk_ops_estimates_cfg_estimates     FOREIGN KEY (cfg_estimate_id)    REFERENCES cfg_estimates(id),
    CONSTRAINT fk_ops_estimates_service_addresses FOREIGN KEY (service_address_id) REFERENCES service_addresses(id)
);

CREATE TABLE ops_programs (
    id                  INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           INT          NOT NULL,
    cfg_program_id      INT          NOT NULL,
    ops_estimate_id     INT          NOT NULL,
    is_active           BOOLEAN      NOT NULL DEFAULT FALSE,
    notes               TEXT,
    start_date          TIMESTAMPTZ  NOT NULL,
    end_date            TIMESTAMPTZ,
    renewal_date        TIMESTAMPTZ,
    canceled_date       TIMESTAMPTZ,
    pending_cancel_date TIMESTAMPTZ,
    frequency           SMALLINT     NOT NULL,
    is_deleted          BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ  NOT NULL,
    modified_at         TIMESTAMPTZ  NOT NULL,
    created_by          UUID         NOT NULL,
    modified_by         UUID         NOT NULL,
    CONSTRAINT fk_ops_programs_tenants       FOREIGN KEY (tenant_id)       REFERENCES tenants(id),
    CONSTRAINT fk_ops_programs_cfg_programs  FOREIGN KEY (cfg_program_id)  REFERENCES cfg_programs(id),
    CONSTRAINT fk_ops_programs_ops_estimates FOREIGN KEY (ops_estimate_id) REFERENCES ops_estimates(id)
);

CREATE TABLE ops_events (
    id             INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      INT         NOT NULL,
    cfg_event_id   INT         NOT NULL,
    ops_program_id INT         NOT NULL,
    is_active      BOOLEAN     NOT NULL DEFAULT FALSE,
    is_deleted     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMPTZ NOT NULL,
    modified_at    TIMESTAMPTZ NOT NULL,
    created_by     UUID        NOT NULL,
    modified_by    UUID        NOT NULL,
    CONSTRAINT fk_ops_events_tenants      FOREIGN KEY (tenant_id)      REFERENCES tenants(id),
    CONSTRAINT fk_ops_events_cfg_events   FOREIGN KEY (cfg_event_id)   REFERENCES cfg_events(id),
    CONSTRAINT fk_ops_events_ops_programs FOREIGN KEY (ops_program_id) REFERENCES ops_programs(id)
);

CREATE TABLE ops_workorders (
    id               INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        INT          NOT NULL,
    ops_event_id     INT          NOT NULL,
    workorder_number VARCHAR(100) NOT NULL,
    status           SMALLINT     NOT NULL,
    route_id         INT          NOT NULL,
    start_date       TIMESTAMPTZ  NOT NULL,
    duration         INT          NOT NULL,
    completed_date   TIMESTAMPTZ,
    canceled_date    TIMESTAMPTZ,
    is_deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ  NOT NULL,
    modified_at      TIMESTAMPTZ  NOT NULL,
    created_by       UUID         NOT NULL,
    modified_by      UUID         NOT NULL,
    CONSTRAINT fk_ops_workorders_tenants    FOREIGN KEY (tenant_id)    REFERENCES tenants(id),
    CONSTRAINT fk_ops_workorders_ops_events FOREIGN KEY (ops_event_id) REFERENCES ops_events(id)
);
