CREATE TABLE customers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INT NOT NULL,
    customer_num VARCHAR(50),
    name VARCHAR(255) NOT NULL,
    customer_type INT NOT NULL DEFAULT 1,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    send_invoice BOOLEAN NOT NULL DEFAULT FALSE,
    email_invoice BOOLEAN NOT NULL DEFAULT FALSE,
    instructions TEXT,
    primary_note TEXT,
    registration_num VARCHAR(100),
    preferred_contact_method VARCHAR(50),
    billing_address_street VARCHAR(255),
    billing_address_city VARCHAR(255),
    billing_address_state VARCHAR(255),
    billing_address_zip VARCHAR(50),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL,
    modified_at TIMESTAMPTZ NOT NULL,
    created_by UUID NOT NULL,
    modified_by UUID NOT NULL,
    CONSTRAINT fk_customers_tenants FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE TABLE customer_contacts (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INT NOT NULL,
    customer_id INT NOT NULL,
    contact_type VARCHAR(50) NOT NULL DEFAULT 'Billing',
    first_name VARCHAR(255),
    middle_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255),
    alternate_emails TEXT,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL,
    modified_at TIMESTAMPTZ NOT NULL,
    created_by UUID NOT NULL,
    modified_by UUID NOT NULL,
    CONSTRAINT fk_customer_contacts_tenants FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_customer_contacts_customers FOREIGN KEY (customer_id) REFERENCES customers(id)
);

CREATE TABLE customer_contact_phones (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id INT NOT NULL,
    customer_contact_id INT NOT NULL,
    phone_type VARCHAR(50),
    phone_number VARCHAR(50),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL,
    modified_at TIMESTAMPTZ NOT NULL,
    modified_by UUID,
    created_by UUID,
    CONSTRAINT fk_customer_contact_phones_tenants FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_customer_contact_phones_customer_contacts FOREIGN KEY (customer_contact_id) REFERENCES customer_contacts(id)
);
