CREATE TABLE outbox_messages (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type   TEXT        NOT NULL,
    payload      JSONB       NOT NULL,
    occurred_at  TIMESTAMPTZ NOT NULL,
    processed_at TIMESTAMPTZ NULL,
    error        TEXT        NULL
);

CREATE INDEX ix_outbox_messages_unprocessed
    ON outbox_messages (occurred_at)
    WHERE processed_at IS NULL AND error IS NULL;
