CREATE TABLE Accounts (
    Id INT NOT NULL PRIMARY KEY IDENTITY,
    Name NVARCHAR(255) NOT NULL,
    IsActive BIT NOT NULL,
    IsDeleted BIT NOT NULL, 
    CreatedAt DATETIME2 NOT NULL,
    ModifiedAt DATETIME2 NOT NULL,
    CreatedBy UNIQUEIDENTIFIER NOT NULL,
    ModifiedBy UNIQUEIDENTIFIER NOT NULL
);
GO

CREATE TABLE Sites (
    Id INT NOT NULL PRIMARY KEY IDENTITY,
    ReferenceNumber NVARCHAR(255) NOT NULL,
    AccountId INT NOT NULL,
    IsDeleted BIT NOT NULL, 
    CreatedAt DATETIME2 NOT NULL,
    ModifiedAt DATETIME2 NOT NULL,
    CreatedBy UNIQUEIDENTIFIER NOT NULL,
    ModifiedBy UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_Sites_Accounts FOREIGN KEY (AccountId) REFERENCES Accounts(Id)
);
GO