CREATE TABLE Customers (
    Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenantId INT NOT NULL,
    CustomerNum VARCHAR(50),
    Name VARCHAR(255) NOT NULL,
    CustomerType INT NOT NULL DEFAULT 1,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    SendInvoice BOOLEAN NOT NULL DEFAULT FALSE,
    EmailInvoice BOOLEAN NOT NULL DEFAULT FALSE,
    Instructions TEXT,
    PrimaryNote TEXT,
    RegistrationNum VARCHAR(100),
    PreferredContactMethod VARCHAR(50),
    BillingAddressStreet VARCHAR(255),
    BillingAddressCity VARCHAR(255),
    BillingAddressState VARCHAR(255),
    BillingAddressZip VARCHAR(50),
    IsDeleted BOOLEAN NOT NULL DEFAULT FALSE,
    CreatedAt TIMESTAMPTZ NOT NULL,
    ModifiedAt TIMESTAMPTZ NOT NULL,
    CreatedBy UUID NOT NULL,
    ModifiedBy UUID NOT NULL,
    CONSTRAINT FK_Customers_Tenants FOREIGN KEY (TenantId) REFERENCES Tenants(Id)
);

CREATE TABLE CustomerContacts (
    Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenantId INT NOT NULL,
    CustomerId INT NOT NULL,
    ContactType VARCHAR(50) NOT NULL DEFAULT 'Billing',
    FirstName VARCHAR(255),
    MiddleName VARCHAR(255),
    LastName VARCHAR(255),
    Email VARCHAR(255),
    AlternateEmails TEXT,
    IsDeleted BOOLEAN NOT NULL DEFAULT FALSE,
    CreatedAt TIMESTAMPTZ NOT NULL,
    ModifiedAt TIMESTAMPTZ NOT NULL,
    CreatedBy UUID NOT NULL,
    ModifiedBy UUID NOT NULL,
    CONSTRAINT FK_CustomerContacts_Tenants FOREIGN KEY (TenantId) REFERENCES Tenants(Id),
    CONSTRAINT FK_CustomerContacts_Customers FOREIGN KEY (CustomerId) REFERENCES Customers(Id)
);

CREATE TABLE CustomerContactPhones (
    Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenantId INT NOT NULL,
    CustomerContactId INT NOT NULL,
    PhoneType VARCHAR(50),
    PhoneNumber VARCHAR(50),
    IsDeleted BOOLEAN NOT NULL DEFAULT FALSE,
    CreatedAt TIMESTAMPTZ NOT NULL,
    ModifiedAt TIMESTAMPTZ NOT NULL,
    CONSTRAINT FK_CustomerContactPhones_Tenants FOREIGN KEY (TenantId) REFERENCES Tenants(Id),
    CONSTRAINT FK_CustomerContactPhones_CustomerContacts FOREIGN KEY (CustomerContactId) REFERENCES CustomerContacts(Id)
);
